[template]
src = "env.tmpl"
dest = "/usr/src/app/config/env"
keys = [
	"API_VPN_SERVICE_API_KEY",
	"AUTH_RESINOS_REGISTRY_CODE",
	"COOKIE_SESSION_SECRET",
	"CONTRACTS_PUBLIC_REPO_OWNER",
	"CONTRACTS_PUBLIC_REPO_NAME",
	"CONTRACTS_PRIVATE_REPO_OWNER",
	"CONTRACTS_PRIVATE_REPO_NAME",
	"CONTRACTS_PRIVATE_REPO_TOKEN",
	"DB_HOST",
	"DB_PASSWORD",
	"DB_PORT",
	"DB_USER",
	"DELTA_HOST",
	"DEVICE_CONFIG_OPENVPN_CA",
	"DEVICE_CONFIG_SSH_AUTHORIZED_KEYS",
	"EXTRA_CONTAINERS",
	"FILES_HOST",
	"HOST",
	"IMAGE_STORAGE_ACCESS_KEY",
	"IMAGE_STORAGE_BUCKET",
	"IMAGE_STORAGE_ENDPOINT",
	"IMAGE_STORAGE_FORCE_PATH_STYLE",
	"IMAGE_STORAGE_PREFIX",
	"IMAGE_STORAGE_SECRET_KEY",
	"JSON_WEB_TOKEN_EXPIRY_MINUTES",
	"JSON_WEB_TOKEN_SECRET",
	"MIXPANEL_TOKEN",
	"PRODUCTION_MODE",
	"REDIS_HOST",
	"REDIS_PORT",
	"REGISTRY2_HOST",
	"SENTRY_DSN",
	"SUPERUSER_EMAIL",
	"SUPERUSER_PASSWORD",
	"TOKEN_AUTH_BUILDER_TOKEN",
	"TOKEN_AUTH_CERT_ISSUER",
	"TOKEN_AUTH_CERT_KEY",
	"TOKEN_AUTH_CERT_KID",
	"TOKEN_AUTH_CERT_PUB",
	"TOKEN_AUTH_JWT_ALGO",
	"VPN_HOST",
	"VPN_PORT",
	"VPN_SERVICE_API_KEY",
	"VPN_GUEST_API_KEY",
	"VPN_CONNECT_PROXY_PORT"
]
